- name: Increase disk
  ansible.builtin.shell: growpart /dev/nvme0n1 4 ; lvextend -r -l 100%FREE /dev/mapper/RootVG-varVol
  ignore_errors: yes

- name: Download docker repo file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker.repo

- name: Install docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: installed

- name: Start Docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: yes

- name: Run Container
  community.docker.docker_container:
    name: "{{ component_name }}"
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/{{ component }}
    state: started
    recreate: true
    ports:
      - "{{ app_port }}:{{ app_port }}"
    env_file: /opt/{{ component_name }}.env